In [79]:
import pandas as pd
import numpy as np
import h3

# TODO
- Miles to km (?)
- Provide a detailed description of the trip dataset such that there are no pending questions.
- Evaluate Aggregation Logic especially in regards to Spatial Analysis and Prediction tasks

## What happened before uploading the CSV:
- Filtering the data for:
    - Pickup/Dropoff Census Tract is not null
    - Trip Seconds/Miles is not 0
    - Removing unneccasssary columns: Fare, Tips, Tolls, Extras, Payment Type, Pickup/Dropoff Centroid Location
- resulting data with 16 columns and 6.041.177 rows

#TODO: Add column description from website here as Markdown

In [80]:
taxi_data = pd.read_csv("../data/Taxi_Trips.csv")
taxi_data

,Trip ID,Taxi ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,Trip Total,Company,Pickup Centroid Latitude,Pickup Centroid Longitude,Dropoff Centroid Latitude,Dropoff Centroid Longitude
0,a1e30fb944a6fd2598a9c3caf0192121f0e39dea,249d932165de24c10140f979fa81b350183cff7ac63099...,04/30/2026 11:45:00 PM,05/01/2026 12:00:00 AM,261.000,"0,4",17031833000,17031833000,28.0,28.0,"$5,00",Globe Taxi,"41,88528132","-87,6572332","41,88528132","-87,6572332"
1,07df4fb41ec699a5287f8a4e64726563bae385fc,fed019ef14a3bfeaa5ef5f523be5d8dc28943952aa66a3...,04/30/2026 11:45:00 PM,05/01/2026 12:00:00 AM,240.000,"0,9",17031833000,17031081800,28.0,8.0,"$5,25",Choice Taxi Association Inc,"41,88528132","-87,6572332","41,89321636","-87,63784421"
2,5d9e23fa8a4beb9d495f5c4c7c00bf33026b561e,fb1ed566274f6a66dfcddbe4c014bbe87ac3516412dfe6...,04/30/2026 11:45:00 PM,05/01/2026 12:00:00 AM,425.000,"1,41",17031833000,17031320400,28.0,32.0,"$8,45",Sun Taxi,"41,88528132","-87,6572332","41,877406123","-87,621971652"
3,e6ba74242fb88764fb6cb5e34a7f399b613c1a6b,3278a0dd17ed3de47adf8cf7236bf8f21f29e62c04394b...,04/30/2026 11:45:00 PM,05/01/2026 12:00:00 AM,1.560,"16,8",17031980000,17031320400,76.0,32.0,"$53,75",Transit Administrative Center Inc,"41,97907082","-87,903039661","41,877406123","-87,621971652"
4,876f1c50d59ac611ff5daca49934a046c951de40,3f365e125eb1d15aae0ae8a4bf53a01191478f26ccf00c...,04/30/2026 11:45:00 PM,05/01/2026 12:00:00 AM,1.297,"17,1",17031980000,17031833000,76.0,28.0,"$47,25",5 Star Taxi,"41,97907082","-87,903039661","41,88528132","-87,6572332"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6041172,a75082c74bf8ae2f97d9811101952ba5de8192aa,50fcee6711df1d794e4f337c99f44abe8109795ec69474...,01/01/2024 12:00:00 AM,01/01/2024 12:00:00 AM,452.000,"0,2",17031081700,17031081700,8.0,8.0,"$5,75",Medallion Leasin,"41,892042136","-87,63186395","41,892042136","-87,63186395"
6041173,63d8c865c01bde9e17e469db6a30e33c8cfe5314,259d38cfdbc9ac6f9bb01f0df740e0ddf4a631a70bbdd6...,01/01/2024 12:00:00 AM,01/01/2024 12:00:00 AM,180.000,"0,3",17031081500,17031081201,8.0,8.0,"$5,25","Taxicab Insurance Agency, LLC","41,892507781","-87,626214906","41,899155613","-87,626210532"
6041174,3c05ccf0732fc338b7c875f9a9779039eaada274,0cbf5c0f6aca3628d77c7b6fe89715757ed402a70b0f8b...,01/01/2024 12:00:00 AM,01/01/2024 12:30:00 AM,1.681,"15,34",17031980000,17031071400,76.0,7.0,"$53,10",Globe Taxi,"41,97907082","-87,903039661","41,922082541","-87,634156093"
6041175,ddcd4d6b7c138bee6841a7800cfbb45f31e6101a,0fdab9be71f6d88e3d3a2e115afc5a33d2bf74153792c5...,01/01/2024 12:00:00 AM,01/01/2024 12:45:00 AM,3.059,"17,44",17031980000,17031320100,76.0,32.0,"$66,30",City Service,"41,97907082","-87,903039661","41,884987192","-87,620992913"
6041176,22208de57c456e7e6ea5f60bdc1746ad300535a9,04b96cbbdcfe5b7cbb6884bc1b922819466f652662ead8...,01/01/2024 12:00:00 AM,01/01/2024 12:30:00 AM,2.214,"18,23",17031980000,17031320100,76.0,32.0,"$60,66",5 Star Taxi,"41,97907082","-87,903039661","41,884987192","-87,620992913"

In [81]:
taxi_data.info()
taxi_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6041177 entries, 0 to 6041176
Data columns (total 16 columns):
 #   Column                      Dtype
---  ------                      -----
 0   Trip ID                     object
 1   Taxi ID                     object
 2   Trip Start Timestamp        object
 3   Trip End Timestamp          object
 4   Trip Seconds                float64
 5   Trip Miles                  object
 6   Pickup Census Tract         int64
 7   Dropoff Census Tract        int64
 8   Pickup Community Area       float64
 9   Dropoff Community Area      float64
 10  Trip Total                  object
 11  Company                     object
 12  Pickup Centroid Latitude    object
 13  Pickup Centroid Longitude   object
 14  Dropoff Centroid Latitude   object
 15  Dropoff Centroid Longitude  object
dtypes: float64(3), int64(2), object(11)
memory usage: 737.4+ MB

,Trip Seconds,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area
count,6.041177e+06,6.041177e+06,6.041177e+06,6.038883e+06,5.954058e+06
mean,3.380790e+02,1.703147e+10,1.703139e+10,3.371160e+01,2.469550e+01
std,2.973048e+02,3.669296e+05,3.339332e+05,2.415009e+01,1.746181e+01
min,1.000000e+00,1.703101e+10,1.703101e+10,1.000000e+00,1.000000e+00
25%,2.987000e+00,1.703108e+10,1.703108e+10,8.000000e+00,8.000000e+00
50%,3.490000e+02,1.703132e+10,1.703132e+10,3.200000e+01,2.800000e+01
75%,5.690000e+02,1.703184e+10,1.703184e+10,3.300000e+01,3.200000e+01
max,9.990000e+02,1.703198e+10,1.703198e+10,7.700000e+01,7.700000e+01

## Change Data types from string to numeric

In [82]:
# Columns to fix data type
cols_to_fix = [
    'Pickup Centroid Longitude', 'Pickup Centroid Latitude',
    'Dropoff Centroid Longitude', 'Dropoff Centroid Latitude',
    'Trip Total', 'Trip Miles'
]

# Check for any NaN values in the coordinate columns before conversion
print(taxi_data[cols_to_fix].isna().sum())

for col in cols_to_fix:
    
    if col == 'Trip Total':
        # Remove the dollar sign and commas from the Trip Total column
        taxi_data[col] = taxi_data[col].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False)
    elif col == 'Trip Miles' or col in ['Pickup Centroid Longitude', 'Pickup Centroid Latitude', 'Dropoff Centroid Longitude', 'Dropoff Centroid Latitude']:
        # Replace the comma with a standard decimal point
        taxi_data[col] = taxi_data[col].astype(str).str.replace(',', '.', regex=False)

    # Convert to numeric
    taxi_data[col] = pd.to_numeric(taxi_data[col], errors='coerce')

# Check for any NaN values in the coordinate columns after conversion
print(taxi_data[cols_to_fix].isna().sum())

Pickup Centroid Longitude       232
Pickup Centroid Latitude        232
Dropoff Centroid Longitude    14311
Dropoff Centroid Latitude     14311
Trip Total                    14575
Trip Miles                        0
dtype: int64
Pickup Centroid Longitude       232
Pickup Centroid Latitude        232
Dropoff Centroid Longitude    14311
Dropoff Centroid Latitude     14311
Trip Total                    14575
Trip Miles                        3
dtype: int64

## Add Column with H3 index

In [83]:
# Method to match with H3 Hexagons Index
# We'll use resolution 8 as a starting point for "discretizing the city"
def get_h3_index(row, lat, lng):
    # If either coordinate is missing (NaN), return None
    if pd.isna(row[lat]) or pd.isna(row[row[lng]]):
        return None
    return h3.latlng_to_cell(lat, lng, 8)

taxi_data['h3_index_pickup'] = [
    # Check if lat and lng are not NaN before converting to H3 index, otherwise return None
    h3.latlng_to_cell(lat, lng, 8) if (lat == lat and lng == lng) else None
    for lat, lng in zip(
        taxi_data['Pickup Centroid Latitude'], 
        taxi_data['Pickup Centroid Longitude']
    )
]

taxi_data['h3_index_dropoff'] = [
    # Check if lat and lng are not NaN before converting to H3 index, otherwise return None
    h3.latlng_to_cell(lat, lng, 8) if (lat == lat and lng == lng) else None
    for lat, lng in zip(
        taxi_data['Dropoff Centroid Latitude'], 
        taxi_data['Dropoff Centroid Longitude']
    )
]

# Check for any NaN values in the new H3 index columns
print("NaN values in H3 index columns:")
print(taxi_data[['h3_index_pickup', 'h3_index_dropoff']].isna().sum())

NaN values in H3 index columns:
h3_index_pickup       232
h3_index_dropoff    14311
dtype: int64

In [84]:
# Drop rows where either pickup or dropoff H3 index is NaN, as these rows cannot be used for spatial analysis 
# and drop columns that are not needed for the analysis
columns_to_drop = [
    'Pickup Centroid Longitude', 'Pickup Centroid Latitude',
    'Dropoff Centroid Longitude', 'Dropoff Centroid Latitude',
    'Pickup Census Tract', 'Dropoff Census Tract', # Maybe use this for spatial analysis
    'Pickup Community Area', 'Dropoff Community Area',
]
taxi_data_processed = taxi_data.drop(columns=columns_to_drop).dropna(subset=['h3_index_pickup', 'h3_index_dropoff'])

taxi_data_processed['Pickup Hour'] = pd.to_datetime(taxi_data_processed['Trip Start Timestamp']).dt.floor('H')
taxi_data_processed['Dropoff Hour'] = pd.to_datetime(taxi_data_processed['Trip End Timestamp']).dt.floor('H')

/var/folders/mb/d7qxmv150dz1wszhty3l250c0000gn/T/ipykernel_85934/1632907597.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  taxi_data_processed['Pickup Hour'] = pd.to_datetime(taxi_data_processed['Trip Start Timestamp']).dt.floor('H')
/var/folders/mb/d7qxmv150dz1wszhty3l250c0000gn/T/ipykernel_85934/1632907597.py:11: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  taxi_data_processed['Pickup Hour'] = pd.to_datetime(taxi_data_processed['Trip Start Timestamp']).dt.floor('H')
/var/folders/mb/d7qxmv150dz1wszhty3l250c0000gn/T/ipykernel_85934/1632907597.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  taxi_data_processed['Dropoff Hour'] = pd.to_datetime(taxi_data_processed['Trip End Timestamp']).dt.floor('H')
/var/folders/mb/d7qxmv150dz1wszhty3l250c0000gn/T/ipykernel_85934/1632907597.py:12: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  taxi_data_processed['Dropoff Hour'] = pd.to_datetime(taxi_data_processed['Trip End Timestamp']).dt.floor('H')

In [85]:
# Create a new df with hourly timestamps in the range of the dataset and all unique H3 indices 
# so we have a complete grid for analysis

# Get the range of timestamps in the dataset
min_timestamp = taxi_data_processed['Pickup Hour'].min()
max_timestamp = taxi_data_processed['Dropoff Hour'].max()

# Create a complete hourly timestamp range
hourly_timestamps = pd.date_range(start=min_timestamp, end=max_timestamp, freq='H')

# Get all unique H3 indices from both pickup and dropoff
unique_h3_indices = pd.unique(pd.concat([taxi_data_processed['h3_index_pickup'], taxi_data_processed['h3_index_dropoff']]))

# Create a complete grid of all combinations of hourly timestamps and unique H3 indices
complete_grid = pd.MultiIndex.from_product(
    [hourly_timestamps, unique_h3_indices], names=['hour', 'h3_index']).to_frame(index=False)

/var/folders/mb/d7qxmv150dz1wszhty3l250c0000gn/T/ipykernel_85934/2688092845.py:9: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly_timestamps = pd.date_range(start=min_timestamp, end=max_timestamp, freq='H')

In [88]:
# Define aggregations specifically for the Pickups
pickup_aggregations = {
    'Total_Trip_Start': ('Trip ID', 'count'),
    'Unique Taxis': ('Taxi ID', 'nunique'),
    'Avg Trip Seconds': ('Trip Seconds', 'mean'),
    'Avg Trip Miles': ('Trip Miles', 'mean'),
    'Avg Fare': ('Trip Total', 'mean'),
    'Most Common Company': ('Company', lambda x: x.mode()[0] if not x.mode().empty else np.nan),
    'Company Count': ('Company', 'nunique')
}

# Define aggregations specifically for the Dropoffs
dropoff_aggregations = {
    'Total_Trip_End': ('Trip ID', 'count')
}

# Perform two separate groupbys
agg_pickups = taxi_data_processed.groupby(
    ['h3_index_pickup', 'Pickup Hour']
).agg(**pickup_aggregations).reset_index()

agg_dropoffs = taxi_data_processed.groupby(
    ['h3_index_dropoff', 'Dropoff Hour']
).agg(**dropoff_aggregations).reset_index()


# Merge the Pickup data into the complete grid
final_grid = complete_grid.merge(
    agg_pickups, 
    left_on=['hour', 'h3_index'], 
    right_on=['Pickup Hour', 'h3_index_pickup'], 
    how='left'
).drop(columns=['Pickup Hour', 'h3_index_pickup'])

# Merge the Dropoff data into the complete grid
final_grid = final_grid.merge(
    agg_dropoffs, 
    left_on=['hour', 'h3_index'], 
    right_on=['Dropoff Hour', 'h3_index_dropoff'], 
    how='left'
).drop(columns=['Dropoff Hour', 'h3_index_dropoff'])

# Fill missing values with 0 for count columns
final_grid['Total_Trip_Start'] = final_grid['Total_Trip_Start'].fillna(0)
final_grid['Total_Trip_End'] = final_grid['Total_Trip_End'].fillna(0)

In [93]:
# Merge POI data into the final grid
pois = pd.read_csv("../data/chicago_pois_agg.csv")
final_grid = final_grid.merge(
    pois, 
    left_on='h3_index', 
    right_on='h3_index',
    how='left'
).drop(columns=['h3_index'])

In [94]:
final_grid

,hour,Total_Trip_Start,Unique Taxis,Avg Trip Seconds,Avg Trip Miles,Avg Fare,Most Common Company,Company Count,Total_Trip_End,poi_count,count_poi_types,poi_type_list,poi_list
0,2024-01-01,2.0,2.0,425.3300,2.400000,1812.500000,City Service,2.0,1.0,72.0,28.0,"school, bicycle_rental, bicycle_rental, bar, a...","Chicago Institute of Technology, Ashland Ave &..."
1,2024-01-01,7.0,7.0,1.7400,17.370000,5821.428571,Flash Cab,6.0,0.0,234.0,40.0,"cafe, newsagent, books, atm, convenience, fast...","Starbucks, Hudson News, Barbara's Bookstore, C..."
2,2024-01-01,8.0,8.0,440.6800,0.587500,1168.500000,Chicago Independents,6.0,5.0,316.0,57.0,"pub, restaurant, copyshop, bar, restaurant, un...","Midtown Kitchen & Bar, Nick's Fishmarket Grill..."
3,2024-01-01,1.0,1.0,2.8790,3.290000,2175.000000,Flash Cab,1.0,0.0,264.0,53.0,"ferry_terminal, university, music_school, gift...","Union Station/Willis Tower, Chicago-Kent Colle..."
4,2024-01-01,15.0,15.0,294.7794,1.155333,1502.666667,Chicago Independents,7.0,7.0,406.0,64.0,"college, art, restaurant, fast_food, hotel, ho...","Loyola Law School, R.H. Love Galleries, Jake M..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9272945,2026-05-01,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,28.0,17.0,"place_of_worship, place_of_worship, department...","Holy Communion Lutheran Church, Smyrna Korean ..."
9272946,2026-05-01,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,14.0,8.0,"school, school, school, bakery, cafe, bicycle_...","Saint Ladislaus School, Mid-America Beauty Sch..."
9272947,2026-05-01,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,23.0,9.0,"place_of_worship, place_of_worship, place_of_w...",Greater New Mount Olivet Missionary Baptist Ch...
9272948,2026-05-01,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,5.0,3.0,"place_of_worship, place_of_worship, place_of_w...","Pure in Heart Missionary Baptist Church, Chris..."
9272949,2026-05-01,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,17.0,9.0,"place_of_worship, place_of_worship, place_of_w...","Church of Christ, Church of God, Youth Center ..."